### ISSUE TITLE
TypeError: Cannot read property 'relevance_score' of undefined

### ISSUE THREAD

**Issue by zeel01** [League-of-Foundry-Developers/Leo-bot#6]
`/package name: dungeon moon`

```
1|leo  | TypeError: Cannot read property 'relevance_score' of undefined
1|leo  |     at Package.checkResults (file:///root/Leo-bot/classes/Package.js:260:44)
1|leo  |     at Package.searchPackages (file:///root/Leo-bot/classes/Package.js:230:45)
1|leo  |     at runMicrotasks (<anonymous>)
1|leo  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
1|leo  |     at async Package.init (file:///root/Leo-bot/classes/Package.js:94:29)
1|leo  |     at async Function.get (file:///root/Leo-bot/classes/Package.js:22:10)
1|leo  |     at async PackageSearch.getPackageResponse (file:///root/Leo-bot/classes/PackageSearch.js:73:15)
1|leo  |     at async PackageSearch.command (file:///root/Leo-bot/classes/PackageSearch.js:56:4)
1|leo  |     at async PackageSearch.handleInteraction (file:///root/Leo-bot/classes/InteractionHandler.js:74:20)
1|leo  |     at async Promise.all (index 1)
```

**Comment by zeel01** [comment]
Seems to be the relevance check against the second result when the second result doesn't exist.
